export const INCREASE_BALANCE = 'INCREASE_BALANCE';
export const DECREASE_BALANCE = 'DECREASE_BALANCE';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const REVERSE_INCREASE = 'REVERSE_INCREASE';
export const REVERSE_DECREASE = 'REVERSE_DECREASE';
